name: Discord Bot Deployment

on:
  push:
    branches:
      - 'release'
      - 'INTERNAL-4-WORKFLOW'

env:
  host: ${{ secrets.SSH_HOST }}
  pswd: ${{ secrets.SSH_PSWD }}
  user: ${{ secrets.SSH_USER }}
  private: ${{ secrets.SSH_PRIVATE_KEY }}
  cf_client: ${{ secrets.CF_CLIENT_ID }}
  cf_secret: ${{ secrets.CF_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.2

      - name: Cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${host}
          username: ${user}
          key: ${private}
          proxy_command: >
            cloudflared access ssh --hostname %h
            --id ${cf_client}
            --secret ${cf_secret}
          script: |
            cd /home/rpastor05/MiKontrol-Client
            echo *
