name: Discord Bot Deployment

on:
  push:
    branches:
      - 'release'
      - 'INTERNAL-4-WORKFLOW'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.2

      - name: Cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            ssh -o ProxyCommand="cloudflared access ssh --hostname ${{ env.SSH_HOST }} --id ${{ secrets.CF_CLIENT_ID }} --secret ${{ secrets.CF_CLIENT_SECRET }}" \
            ${{env.SSH_USER}}@${{env.SSH_HOST}} << 'EOF'
              cd /home/rpastor05/MiKontrol-Client
              echo *
            EOF
